### ISSUE TITLE
Desconectando

### ISSUE THREAD

**Issue by jeffersoncgo** [Ramys/Iptv-Brasil-2022#10]
Oi, o tempo todo, todos os canais ficam desconectando.
Não costumo mexer muito com isso, ai toda hora quando desconecta, o player fecha, e recomeça o filme/série tudo de novo.

**Comment by Ramys** [comment]
> Oi, o tempo todo, todos os canais ficam desconectando. Não costumo mexer muito com isso, ai toda hora quando desconecta, o player fecha, e recomeça o filme/série tudo de novo.

Qual lista?

**Comment by jeffersoncgo** [comment]
Estou usando a "Canais2022.m3u8", a "CanaisB5.m3u8" não pegou pra mim, fica tudo fora, só a "Canais2022.m3u8" que pega, mas fica desconectando

**Comment by Ramys** [comment]
Aqui está online normalmente.
Verifique sua conexão e velocidade de rede .
