### ISSUE TITLE
consegue me ajudar a separar o conteudo, pois fica tudo junto. Filmes, séries e canais

### ISSUE THREAD

**Issue by Etavares1301** [Ramys/Iptv-Brasil-2022#12]
**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [por exemplo iOS]
 - Navegador [por exemplo, cromo, safári]
 - Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo, navegador de ações, safári]
 - Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Ramys** [comment]
Vc quer somente os Premieres?
Mas vc tá usando onde essa lista, em navegador ou aplicativo, e qual aplicativo?

**Comment by Ramys** [comment]
@Etavares1301

**Comment by Etavares1301** [comment]
eu percebi que os canais premier estão travando no seu app(navegador) quanto em qualquer outro.
estou usando no xiptv, televiso

**Comment by Ramys** [comment]
Qual lista?

**Comment by Etavares1301** [comment]
https://raw.githubusercontent.com/Ramys/Iptv-Brasil-2022/master/Canais2022.m3u8

**Comment by Ramys** [comment]
Amanhã irei atualizar o novo id..
Use esse novo.

Login: 0672648180
Senha: fireurl.co
Url: http://b5.vc:80
@Etavares1301

**Comment by Etavares1301** [comment]
obrigado!
pode criar um login para colocar no aparelho na casa da minha mãe, por favor!
ou pode usar esse?

**Comment by Ramys** [comment]
Pode usar esse mesmo sem problemas.

**Comment by Etavares1301** [comment]
beleza, obrigado!
na tv samsumg só tem o app smart up, tem como liberar acesso pra esse app?

**Comment by Futura1976** [comment]
alguem sabe pq parou de funcionar obrigado
