### ISSUE TITLE
Falha e nos canais

### ISSUE THREAD

**Issue by Malk41** [Ramys/Iptv-Brasil-2022#13]
**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [por exemplo iOS]
 - Navegador [por exemplo, cromo, safári]
 - Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo, navegador de ações, safári]
 - Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.
Amigo.
Seu Player tv é muito bom, mas não é possível assistir os canais com estabilidade, eles sempre cai.
O que poderia fazer p melhor essa questão?
Valeu

**Comment by Malk41** [comment]
Amigo.
Seu Player e top, mas os canais cai a todo instante, o que poderia melhorar?
Valeu

**Comment by Ramys** [comment]
Se vc usa o windows , experimente instalar o aplicativo..https://mega.nz/file/6htXCQ6Z#-Vn4GPhlEioREmUM6aTLcxaJ_v5IV3wruQhgzXh745M

**Comment by Malk41** [comment]
Eu preciso usar na TV.
E esse Player Cx é o ideal, quanto vc cobra mensal em uma lista sem
travamento?

Em qua., 25 de mai. de 2022 14:31, Ramys ***@***.***>
escreveu:

**Comment by Ramys** [comment]
Bom...
Eu lhe indico comprar uma tv box, até pq a tv não tem o mesmo sistema de um Android..
Se vc usar essa lista em uma tv box ou celular , verá que é muito difícil os travamentos..
Eu uso uma lista que é partilhada com ao menos 98 pessoas...

**Comment by Ramys** [comment]
Os aplicativos instalados tanto na box quanto ao pc , tem um HW que faz a lista rodar sem travas..

**Comment by xicobiu** [comment]
> Os aplicativos instalados tanto na box quanto ao pc , tem um HW que faz a lista rodar sem travas..

Qual o app pra android?

**Comment by Malk41** [comment]
Peço desculpa pela insistência.
Mas como posso ter um Player.cx e fazer minha própria lista?
É possivel?

Em qua., 25 de mai. de 2022 16:31, Biu ***@***.***> escreveu:

**Comment by Malk41** [comment]
> eço desculpas pela insistência. Mas como posso ter um Player.cx e fazer minha própria lista? É possivel?

**Comment by Ramys** [comment]
@Malk41 
Vc teria que entender um pouco de programação e etc.

**Comment by Ramys** [comment]
@xicobiu 
Esse aqui
https://mega.nz/file/potQmLYJ#jyuLovZ6SxEzZxz_kP-XQxHDsxSkDEKcHWVTJQKZVKY

**Comment by Ramys** [comment]
@xicobiu 
https://mega.nz/file/potQmLYJ#jyuLovZ6SxEzZxz_kP-XQxHDsxSkDEKcHWVTJQKZVKY

**Comment by xicobiu** [comment]
Testei o app do andodrid e realmente os canais ficam só recarregando. O canal não segura.

**Comment by xicobiu** [comment]
> @xicobiu Use essa lista Login: Sidy171 Senha:5p9tps3d6sr Url: http://tv.factoryiptv.com:80

Esse segurou os canais de boa! Mas o 1º tem qualidade maior de imagem.

Tem essa versão pra android?

**Comment by Ramys** [comment]
@xicobiu 
54983186415 
gzAK4
http://pfsv.io:80

**Comment by xicobiu** [comment]
> @xicobiu 54983186415 gzAK4 http://pfsv.io:80

Nao consegui logar no IPTV Stream Player.
Tem versão pra android? no app não tem opção de mudar o URL.

**Comment by Ramys** [comment]
Man, esse aplicativo pode instalar várias lista...
Na tela inicial tem a opção.
