### ISSUE TITLE
whatsapp

### ISSUE THREAD

**Issue by Malk41** [Ramys/Iptv-Brasil-2022#14]
Olá Amigo.
Qual seu whatsapp?

**Comment by Malk41** [comment]
Vc tem um programa instável para tv online?
Quanto vc cobra?

Em ter., 24 de mai. de 2022 21:22, Biu ***@***.***> escreveu:

**Comment by Malk41** [comment]
Digo na web mesmo igual esse palyer.cx que vc disponibiliza, mas um que nao caia os canais.
Esse player.cx é muito bom mas os canais reconecta a todo instante.

**Comment by Pokye** [comment]
> Digo na web mesmo igual esse palyer.cx que vc disponibiliza, mas um que não caia os canais. Esse player.cx é muito bom mas os canais reconecta a todo instante.

isso pq a lista dos canais que o Ramys disponibilizou só pode ser usado por ate 5 pessoas simultâneas, se outra pessoa tentar assistir vai cair com alguém dos 5. 

Se vc não quer q isso aconteça, é só comprar uma lista IPTV fixa somente para você. Pois a lista que o Ramys está compartilhando é aberta para todo mundo usar, então obviamente vai ficar caindo por causa de muita gente assistindo.

**Comment by Ramys** [comment]
Instale esse aplicativo em seu computador...
https://mega.nz/file/6htXCQ6Z#-Vn4GPhlEioREmUM6aTLcxaJ_v5IV3wruQhgzXh745M

Nele vc pode usar qualquer lista de diferentes empresas.

**Comment by xicobiu** [comment]
> Instale esse aplicativo em seu computador... https://mega.nz/file/kt1y1bIS#-Vn4GPhlEioREmUM6aTLcxaJ_v5IV3wruQhgzXh745M
> 
> Nele vc pode usar qualquer lista de diferentes empresas.

![image](https://user-images.githubusercontent.com/28604497/170362684-e98b56cb-2877-4530-87a2-6e1dbef75a08.png)

Não entra! Tá faltando algo?

**Comment by Ramys** [comment]
@xicobiu 
URL
http://b5.vc:80
