### ISSUE TITLE
Login e Senha não carrega

### ISSUE THREAD

**Issue by Robstabank** [Ramys/Iptv-Brasil-2022#15]
Olá Ramys, tudo bem?
O login e senha que você disponibilizou para a club tv não carrega mais.
Eu entro no app(celular e tv) e só fica na tela de atualização, e logo após, não carrega mais canais nem filmes e séries.
Poderia verificar por gentileza?
Muito obrigado!

**Comment by Ramys** [comment]
Oi meu caro , esta em manutenção...
 Em breve on novamente...
Aguardemos!

**Comment by Ramys** [comment]
Use esse login secundário.
Login : Sidy171
Senha: 5p9tps3d6sr
URL: http://tv.factoryiptv.com:80

**Comment by Robstabank** [comment]
Ah, tá certo então.
Muito obrigado.

**Comment by Ramys** [comment]
@Robstabank

**Comment by Ramys** [comment]
Verifique ai , e me avise ok..

**Comment by Robstabank** [comment]
Funcionando perfeitamente! Obrigado!

**Comment by Ramys** [comment]
Assim q voltar eu aviso..

**Comment by Ramys** [comment]
Login : 54983186415
Senha : gzAK4
Url : http://pfsv.io:80
Adicione esse também
@Robstabank

**Comment by Robstabank** [comment]
Obrigado, essa lista também está funcionando bem!

**Comment by Ramys** [comment]
@Robstabank , lista B5 on novamente...
Atualizada..
