### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by Brunowilliang** [Ramys/Iptv-Brasil-2022#16]
Olá Ramys, preciso entrar em contato com vc, me envie um email por favor brunowilliang@icloud.com ou entre em contato .

**Comment by Ramys** [comment]
Vc é o cara do WoW Brasil?

**Comment by Brunowilliang** [comment]
que isso? não kkk

**Comment by Brunowilliang** [comment]
gostaria de saber mais sobre essa lista, como que tu fez? e vc tem intenção de me ajudar num projeto que gostaria de desenvolver

**Comment by Ramys** [comment]
Bom...essas listas são retiradas da internet , eu tenho uns acessos liberados e etc...
Eu ando um pouco sem tempo esses dias , irei mudar de estado e ultimamente tá bem puxado...
Mas poderia me adiantar sobre?

**Comment by Brunowilliang** [comment]
sou dev React e React Native, seria para desenvolver um app com essa lista (se puder claro), porém o único problema é se ela sair do ar e outros problemas que gostaria mto de falar com vc kkk

**Comment by Brunowilliang** [comment]
então, seria essa e outras perguntas que preciso falar com vc.
só com essa lista eu consigo transmitir ilimitado? ou tem algum limite?
seria com login e senha, tem algum problema?
vc tem discord?

**Comment by Ramys** [comment]
https://github.com/sajjadjaved01/iptv
Nesse projeto vc poderia fixar já a lista , com um login e senha .

**Comment by Ramys** [comment]
Já entro em contato com vc..

**Comment by Brunowilliang** [comment]
Beleza, estou no aguardo

**Comment by isanat** [comment]
olá! considere aceitar doações em criptomoedas .

eu estou tentando usar a lista no app da tv porque parece que não funciona m3u8

**Comment by Brunowilliang** [comment]
Fica tranquilo Ramys, tudo no seu tempo! e obrigado

**Comment by Mvmozzer** [comment]
Oi Ramys, Tudo Bom? estou testando o http://player.cx/live.php <<  É normal ficar recarregando toda hora? O canal para sozinho e dps volta

**Comment by isanat** [comment]
As outras listas sua então é pago e esta aqui somente uma degustação, certo ?

**Comment by Ramys** [comment]
@isanat 
Isso...
Lembrando que eu não crio as listas..
Mas tenho alguém q revende a lista .

**Comment by Ramys** [comment]
@Brunowilliang 
Já q adiciono vc no Orkut :stuck_out_tongue:

**Comment by Ramys** [comment]
@Brunowilliang
Mandei um email , via Yahoo..
Kashmir

**Comment by Brunowilliang** [comment]
Oi @Ramys eu te respondi o email

**Comment by Adieldson15** [comment]
Amigo boa noite essa lista da club e com conexão ilumitada outra coisa vc
sabe algum jeito de pegar fonte de canais de SERVIDOR iptv

Em qui., 2 de jun. de 2022 18:21, Bruno Willian Garcia <
***@***.***> escreveu:

**Comment by Ramys** [comment]
@Brunowilliang, fala meu caro ainda não..eu abro ele geralmente no meu pc..
Estou no hospital desde ontem , infecção na garganta e de tudo um bocado....assim que eu tiver alta eu te respondo.

**Comment by Ramys** [comment]
@Adieldson15 
Vc pode usar o iptv hit.... com combos de login e senha...existe all video explicando no YouTube.

**Comment by nicholasstorck** [comment]
cara qual o melhor jeito de assistir iptv sem travar?
