### ISSUE TITLE
Afastamento Breve ( Espero)


### ISSUE THREAD

**Issue by Ramys** [Ramys/Iptv-Brasil-2022#17]
Estou com alguns problemas de saúde ,  e nesse momento estarei cuidado de mim..
Algumas complicações se deram esses dias..
Espero em breve retornar e ajudar à todos.
 Obrigado pela a compreensão.

**Comment by Adieldson15** [comment]
Força mesmo tmj

Em sáb., 4 de jun. de 2022 19:51, Ramys ***@***.***> escreveu:

**Comment by Malk41** [comment]
Força meu amigo, que sua recuperação seja rápida e eficiente, Deus esta no comando.

**Comment by jeffersoncgo** [comment]
Força amigo, que você tenha uma ótima recuperação

**Comment by Malk41** [comment]
Ramys.
Vc tem pix p doação, na sequência gostaria de uma lista de canais se
possível.
Manda no meu email caso tenha

Em dom., 12 de jun. de 2022 12:05, Ramys ***@***.***>
escreveu:

**Comment by Ramys** [comment]
Me passa seu email..
@Malk41

**Comment by Ramys** [comment]
Quando precisar de ajuda ou algo do tipo, abra im ticket novo...
Assim eu consigo visualizar mais rápido..

**Comment by Malk41** [comment]
***@***.***

Em sáb., 9 de jul. de 2022 17:39, Ramys ***@***.***> escreveu:

**Comment by Ramys** [comment]
Abre um ticket novo... pois não mostra seu email..
