### ISSUE TITLE
Sem acesso.

### ISSUE THREAD

**Issue by Marco4raujo** [Ramys/Iptv-Brasil-2022#19]
Ramys, não estou conseguindo acesso ao sistema.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/99364091/173641724-97f35d3a-042c-4e79-aa88-d5b154c6cf3b.png">

Poderia verificar o que aconteceu?
abcs.

**Comment by Ramys** [comment]
Mudou o dns , instale esse apk q é da club..
É a mesma lista só q a url mudou e eu ainda n peguei..
Estou doente e sem acesso ao meu pc..
https://mega.nz/file/potQmLYJ#jyuLovZ6SxEzZxz_kP-XQxHDsxSkDEKcHWVTJQKZVKY
Nesse apk vc usa somente login e senha, n precisa da url.

**Comment by Ramys** [comment]
Achei a url nova , n precisa instalar o apk

**Comment by Ramys** [comment]
Mudou a url , na tela inicial adicione uma nova url com mesmo login e senha..
Url : http://acsc.cc:80

**Comment by Marco4raujo** [comment]
Ramys 

Agora não tem mais o aplicativo do IPTV Smarters no Apple TV. 
Mudou ele também? 
Abcs 

Marcos Araújo

**Comment by Ramys** [comment]
@Marco4raujo , isso eu n sei te responder..
Procure outro apk parecido..
