### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by gustaa7** [Ramys/Iptv-Brasil-2022#20]
Ramys, meus parabéns pelo seu trabalho com essa lista IPTV, e fantástica funciona muito bem (apesar de dura somente alguns dias, mas entendo que elas são obtidas de terceiros)… aquela que vc disponibiliza pela web de tempo ilimitado também é muito boa (algumas vezes se colocar em tela cheia o player para e tenta novamente em 5s, e também não dá pra ver na TV BOX por algum app de iptv)
Mas de qualquer forma eu apoio seu trabalho já que é feito de forma gratuita e irei contribuir com prazer para que o mesmo continue… um abraço!! o

**Comment by Ramys** [comment]
Olá meu caro..
Tenho sim um apk para tv box..
Vou linkar para vc.

**Comment by Ramys** [comment]
Esse apk é da club..ele pede somente login e senha..
https://mega.nz/file/vdkxyYgY#BjEU4mPjWNw3Kr1d1YmIvHFuCVjflEfFZBS9X6S4HNI
Vc usa o login da primeira lista (B5)

**Comment by Ramys** [comment]
@gustaa7
