### ISSUE TITLE
Listas pararam

### ISSUE THREAD

**Issue by Robstabank** [Ramys/Iptv-Brasil-2022#21]
Olá Ramys, boa noite!
Espero que esteja bem e recuperado.
Bom, algumas listaram pararam de carregar os canais.
As que eu verifiquei são a Canais2022; CanaisB5 e dgbr.
(Se elas estiverem funcionando, desconsidere. Eu devo ter feito alguma besteira kkkk)
Obrigado.

**Comment by Ramys** [comment]
Não tá chegando notificação quando alguém abre ticket..
Vou atualizar...
Obrigado por avisar.

**Comment by eduardotuf** [comment]
Boa tarde Ramys,
Essa Lista (CanaisB5.m3u8- http://acsc.cc) está travando muito a cada 30s e 1m, se tornando impossível assistir.
Vou testar a Lista VLC, pra ver se não fica travando.
Obs: A 1º lista (Canais2022.m3u8 - tv.factoryiptv.com:80), ela era muito boa não travava, é uma pena que caiu e está offline.

**Comment by Ramys** [comment]
Acabo de chegar em casa , vou atualizar as listas

**Comment by Ramys** [comment]
> Olá Ramys, boa noite! Espero que esteja bem e recuperado. Bom, algumas listaram pararam de carregar os canais. As que eu verifiquei são a Canais2022; CanaisB5 e dgbr. (Se elas estiverem funcionando, desconsidere. Eu devo ter feito alguma besteira kkkk) Obrigado.

Atualizados..

**Comment by Ramys** [comment]
> Boa tarde Ramys, Essa Lista (CanaisB5.m3u8- http://acsc.cc) está travando muito a cada 30s e 1m, se tornando impossível assistir. Vou testar a Lista VLC, pra ver se não fica travando. Obs: A 1º lista (Canais2022.m3u8 - tv.factoryiptv.com:80), ela era muito boa não travava, é uma pena que caiu e está offline.

Atualizados.
