### ISSUE TITLE
Ajude Urgente

### ISSUE THREAD

**Issue by Othernation** [Ramys/Iptv-Brasil-2022#23]
Saudações nobre amigo
há algumas semanas você me passou login e senha com DNS marotíssimo para utilizar na tv

Blz pura, funcionou ultra..

Mas perdi a senha. kkkkk
O login era 132115
Sem querer pedir demais, mas enfim, se puder manda a senha de novo.
valeu grande irmão, gde abraço

Ah eu sou o Hermantraut do WOW-BR 

Valeu

**Comment by Ramys** [comment]
Fala man kkk
Perdeu veii ....
Me passa seu email q já lhe envio..
@Othernation .

**Comment by Othernation** [comment]
Blz pura!
anacletoainer@gmail.com

Agradeço a atenção nobre amigo

**Comment by Ramys** [comment]
Mandei

**Comment by Ramys** [comment]
Dá uma olhada lá..

**Comment by Alfredo2190** [comment]
Caiu a lista Ramys...A Brasil 2022 m3u8...
O teim que ser assinante?

**Comment by Ramys** [comment]
@Alfredo2190 
Aqui tá normal..
Acabei de olhar.
Verifique ai, por favor.
