### ISSUE TITLE
E-mail 

### ISSUE THREAD

**Issue by Malk41** [Ramys/Iptv-Brasil-2022#25]
Segue meu e-mail
malkklan@gmail.com

**Comment by Ramys** [comment]
Enviado..
Por favor não repassar...
Obrigado.

**Comment by Malk41** [comment]
Blz

Em sáb., 9 de jul. de 2022 19:55, Ramys ***@***.***> escreveu:

**Comment by Ramys** [comment]
:+1:

**Comment by RodrigoRVA** [comment]
Valeu mano
Ótimo trabalho
Vou fazer uma doação pra vc mano, pq vc e foda

Em sáb, 9 de jul de 2022 19:55, Ramys ***@***.***> escreveu:

**Comment by Ramys** [comment]
@RodrigoRVA , vc é o @Malk41?

**Comment by Malk41** [comment]
O malk sou eu Ramys.
To no aguardo,, não consigo fazer doação pelo método da página.

**Comment by Ramys** [comment]
Humm..
Tente pix ...
No email q mandei tem um email q é a chave pix. 
josimarl5@*******

**Comment by RodrigoRVA** [comment]
Não mano, só um admirador do teu trabalho mano, e uma sugestão, era bom vc
deixar pix, pq fica mais fácil pra fazer doação mn

Em sáb, 9 de jul de 2022 20:49, Ramys ***@***.***> escreveu:

**Comment by Ramys** [comment]
Vou adicionar essa chave ..

**Comment by Malk41** [comment]
Não encontrei a chave, por isso ainda não fiz.
Malk41

**Comment by Ramys** [comment]
@Malk41 

Use essa..

602d4c83-fceb-4eb3-8f1a-70af606b571b

**Comment by Malk41** [comment]
Pronto mano, feito.

**Comment by Ramys** [comment]
Agradeço pela a ajuda..
Muito obrigado , irmão..
Qualquer dúvida me chama aqui, e digite o @ antes no meu nick que chega um email me informando..

**Comment by Malk41** [comment]
@Ramys eu ja vou pedir, quando tiver um tempinho atualiza a lista de canais2022 estao off , valeu.

**Comment by Ramys** [comment]
Vou ver aqui a lista canais2022 , pere..

**Comment by Ramys** [comment]
Tem razão ,  irei atualizar..
Mas add outras listas abaixo , use elas tb...
Vlws por reportar.
