### ISSUE TITLE
Canais2022.m3u8 OFF

### ISSUE THREAD

**Issue by Malk41** [Ramys/Iptv-Brasil-2022#27]
Olá Amigo,

Os Canais estão off Canais2022.m3u8.

Valeu

**Comment by Ramys** [comment]
Vou achar um tempo pra atualizar todas...
Tá meio corrido esses dias , nem consigo ligar meu pc..

**Comment by Ramys** [comment]
Hoje eu atualizo as listas..

**Comment by Malk41** [comment]
Joia meu amigo.

**Comment by Ramys** [comment]
[Malk41](https://github.com/Malk41) , lista online com conexão 10 IPS!

Obrigado por reportar.
