### ISSUE TITLE
Acesso clubTV

### ISSUE THREAD

**Issue by Robstabank** [Ramys/Iptv-Brasil-2022#28]
Olá Ramys, tudo bem?
Até o dia de hoje eu estava usando um acesso ilimitado do clubTV, pra ver filmes, séries, e era muito bom. Mas fui deslogado e meu acesso parece que foi expirado.
Eu queria saber se eu pagar algum valor via pix, você conseguiria algum outro acesso ilimitado? Pois era muito bom.
Obrigado.

**Comment by Robstabank** [comment]
Consegui resolver, foi burrice minha kkkk
Mas de qualquer forma, pra alguma ocasião futura, seria legal saber um valor que você aceita pra esse tipo de acesso.
Obrigado.

**Comment by Ramys** [comment]
@Robstabank , qual acc da club vc usa, 132?

**Comment by Robstabank** [comment]
Olá @Ramys eu estou usando esse user: 0672648180

**Comment by Ramys** [comment]
Ahhh..
Tá travando?

**Comment by Robstabank** [comment]
Os canais ao vivo costuman travar bastante, mas pra filmes e séries é maravilhoso, não tenho do que reclamar.

**Comment by Ramys** [comment]
Passa seu email ai q nós resolve isso

**Comment by Robstabank** [comment]
dtbnr.01@gmail.com
Desculpa a demora @Ramys

**Comment by Ramys** [comment]
Malz a demora , já q mando um esquema esquematizado da hora pra vc..kkk

**Comment by Robstabank** [comment]
Beleza! Fico no aguardo kk
