### ISSUE TITLE
Iptv

### ISSUE THREAD

**Issue by Hugox01** [Ramys/Iptv-Brasil-2022#29]
Ramys, amigo fiz uma doação através do e-mail, hugoxturbo@gmail.com, gostaria de um login e senha válido do Iptv. Fiz pagamento via boleto, se precisar do comprovante posso enviar.
Obrigado desde já.

**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [por exemplo iOS]
 - Navegador [por exemplo, cromo, safári]
 - Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo, navegador de ações, safári]
 - Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Ramys** [comment]
Me passa seu email , meu carom

**Comment by Ramys** [comment]
Irei enviar

**Comment by Hugox01** [comment]
Bom dia .
Neste endereço de e-mail mesmo:
***@***.***





Em seg., 25 de jul. de 2022 às 07:44, Ramys ***@***.***>
escreveu:

**Comment by Ramys** [comment]
Acabei de enviar...
Obrigado!
