### ISSUE TITLE
Acesso clubTV

### ISSUE THREAD

**Issue by Robstabank** [Ramys/Iptv-Brasil-2022#30]
Oi Ramys, tudo bem?
Então, meu acesso que eu tinha da clubTV agora sim foi pra vala kkkk
Me manda no meu email como eu faço pra ter um acesso com você, e os valores, por favor?

dtbnr.01@gmail.com

Fico no aguardo! Abraço!

**Comment by Ramys** [comment]
Enviando..

**Comment by Ramys** [comment]
@Robstabank..
Já é..
Olha seu email.

**Comment by Robstabank** [comment]
Opa, chegou aqui!
Muito muito obrigado!!

**Comment by Robstabank** [comment]
Resolvido!

**Comment by area189** [comment]
O que é **CLUBTV** ?
