### ISSUE TITLE
Canais2022.m3u8 Parando

### ISSUE THREAD

**Issue by Malk41** [Ramys/Iptv-Brasil-2022#32]
Olá Ramys
Pode ser normal mas a lista Canais2022, tem travado a cada 1s.
Blz valeu Abraços

**Comment by Ramys** [comment]
Vou mudar a lista..
Obrigado por avisar.

**Comment by Ramys** [comment]
Ainda não atualizei , irei fazer hj....

**Comment by Alfredo2190** [comment]
Obrigadoooo Ramys....ficou certo e otimo...🙌🙌🙌

**Comment by Ramys** [comment]
Firmeza ...
Vlws.
