### ISSUE TITLE
Você pode disponibilizar a URL M3U

### ISSUE THREAD

**Issue by Etavares1301** [Ramys/Iptv-Brasil-2022#34]
Bom dia!
o único aplicativo gratuito da minha tv que funciona está pedindo a url m3u, você pode disponibilizar, por favor
# @Ramys

**Comment by Pokye** [comment]
Escolha a lista no inicio, e clique em **RAW**
![image](https://user-images.githubusercontent.com/98105181/187231998-3ebffa9c-476a-4770-87ac-99eebe68221e.png)
e o link do m3u vai ser o que vai aparecer na sua barra de endereço:
![image](https://user-images.githubusercontent.com/98105181/187232182-80388cd6-a53f-40a6-b3d6-734197fda989.png)

**Comment by Ramys** [comment]
Resolvido?

**Comment by Etavares1301** [comment]
Sim, obrigado

**Comment by Ramys** [comment]
Firme...
É nois..
