### ISSUE TITLE
Canais Param a Exibição Após 1/2 minutos

### ISSUE THREAD

**Issue by charliedamon** [Ramys/Iptv-Brasil-2022#36]
Olá, boa noite.

Todas as listas que eu testo e funciona no VLC e Kodi, após dar play no canal, abre normalmente e funciona sem travar por 1 ou 2 minutos e depois fecha.

Fiz o teste no VLC e Kodi, na TV Box.

Fiz o teste no Windows pelo VLC e Kodi.

E o teste em um Mac, VLC e Kodi.

Internet de 450MB, Wifi e Cabeada.

O que pode ser isso?

Grato por disponibilizar as listas. Ótimo trabalho!

**Comment by Ramys** [comment]
Boa noite , não indico vlc e kodi ..
Vou passar um apk de Android para tv box e windows

**Comment by Ramys** [comment]
Windows ..
https://mega.nz/file/h9NkVRgB#m9ZHCvPNUBEeBzgxdpLuzxuMvkreKSejGrSbAcblpMs

**Comment by Ramys** [comment]
Resolvido??

**Comment by charliedamon** [comment]
Vou fazer o teste amanhã na TV box e reporto o resultado. Grato pela atenção.

**Comment by charliedamon** [comment]
Eu instalei esse apk, mas ele pede usuário, senha e url de login. Eu baixei a sua lista de canais m3u8. Como uso nesse app?

**Comment by felipeavilis** [comment]
Neste App nao precisa da lista. Eu queria usar no VLC, mas o canal cai a cada 30seg.

**Comment by Alissonfnxntc224** [comment]
O meu tá funcionando a "lista reduzida", não tá travando

Em sex., 2 de dez. de 2022 14:59, Felipe Amaral ***@***.***>
escreveu:
