### ISSUE TITLE
Carregamento demorado lista completa 

### ISSUE THREAD

**Issue by area189** [Ramys/Iptv-Brasil-2022#37]
A lista **completa** 2022 demora muito para carregar no KODI.

Faço uso do aparelho **IzyPlay** - Android TV

Você me indica algum ADDON ? Alguma forma de fazer esse carregamento mais rápido ?

**Comment by gustaa7** [comment]
Cara, sai desse Kodi! 
E um app pesado muito lento pra carregar canais de TV e Filmes, independentemente do addon... Baixa o APK do IPTV SMARTERS PRO ou até mesmo qualquer outro app direto da própria loja do google que tenha suporte a lista m3u8 ou xcode stream video.

**Comment by Ramys** [comment]
Kodi é osso kk

**Comment by area189** [comment]
@Ramys  , a lista que você me passou pro KODI é a mesma que me passou pro  IPTV SMARTERS ?

**Comment by Ramys** [comment]
@area189 
Te passei algumas , vc pode usar o apk que te mandei...
Vc usa login, senha e url

**Comment by area189** [comment]
> @area189 Te passei algumas , vc pode usar o apk que te mandei... Vc usa login, senha e url

**Sim** , essas listas são as mesmas do KODI?

**Comment by Ramys** [comment]
Tem uma que não , é fixa um ip..

**Comment by Ramys** [comment]
Essa aqui para KODI
https://tinyurl.com/mpw3cvhr

**Comment by area189** [comment]
> Essa aqui para KODI https://tinyurl.com/mpw3cvhr

**Testando**

**Comment by Ramys** [comment]
> > Essa aqui para KODI https://tinyurl.com/mpw3cvhr
> 
> Essa lista só tem 18 canais. **Canal desconhecido** é o que aparece. @Ramys

Lista corrigida..
link url : https://tinyurl.com/mpw3cvhr

@area189

**Comment by rogerio957** [comment]
Consegui um link com canais e filmes em 3D tudo a funcionar 100% eu uso uma tv LG em 3D e uso oculos originais 
Atenção só conseguem ver em 3D quem tiver uma tv própria com um comando com tecla 3d 
eu consigo ver os canais que estao em 3D e vejo filmes todos no ano 2011 altura que existia o 3d 
os 3d sao todos SBS originais sem programa vejo tudo fora da tela meus netos adoram fica fora da tela 1 metro incrivel sempre adorei  um abraço

**Comment by Etavares1301** [comment]
Fala Mano.
Pode me passar a lista 3d, por favor


Em qua, 19 de out de 2022 13:19, rogerio ***@***.***>
escreveu:
