### ISSUE TITLE
Lista 

### ISSUE THREAD

**Issue by area189** [Ramys/Iptv-Brasil-2022#38]
Bom dia , 

Você pediu para reportar em caso de erro:

Estou usando no **TiviMate IPTV Player**  já testei também em outros.

https://tinyurl.com/2xajv67n
https://tinyurl.com/bde7ys3s
https://tinyurl.com/mpw3cvhr
https://tinyurl.com/mry6y8k3

**Estou testando as listas e a maioria dos canais OFF**

**Comment by Ramys** [comment]
Já que verifico.
Obrigado

**Comment by area189** [comment]
Alguma lista **ON**  nesse momento ? ( Não precisa ser pra KODI ) .

**Comment by Ramys** [comment]
> Alguma lista **ON** nesse momento ? ( Não precisa ser pra KODI ) .

Todas as que vc mencionou estão online novamente.
