### ISSUE TITLE
Lista IPTV travando a cada 1 minuto

### ISSUE THREAD

**Issue by eduardotuf** [Ramys/Iptv-Brasil-2022#39]
Boa tarde, a Lista Starplay está travando a cada minuto, já testei vários aplicativos IPTV, na TV LG SSIPTV, no celular Android VLC, SMARTERS PLAYERS, XCIPTV, SIMPLE IPTV. 

Todas as listas travam comigo, isso acontece só comigo???

**Comment by Ramys** [comment]
Testa outra lista ai pra ver se é só com vc, e me avisa.

**Comment by eduardotuf** [comment]
> Testa outra lista ai pra ver se é só com vc, e me avisa.

Qual Lista que vc indica? Que vc já tenha testado e não está travando.

**Comment by Ramys** [comment]
> > Testa outra lista ai pra ver se é só com vc, e me avisa.
> 
> Qual Lista que vc indica? Que vc já tenha testado e não está travando.

Bom...
teste a api (https://github.com/Ramys/Iptv-Brasil-2022/blob/master/api.m3u8)
