### ISSUE TITLE
Problemas para abrir os canais

### ISSUE THREAD

**Issue by ZeReis1** [Ramys/Iptv-Brasil-2022#40]
Esta dando acesso negado aqui, não consigo acessar os canais! Existe um player IPTV especifico para abrir? Você poderia estruturar um simples passo a passo de como usar. Desde já agradeço.

**Comment by ZeReis1** [comment]
![Capturar](https://user-images.githubusercontent.com/116528631/197427230-3f28cff8-b694-4e0d-a55a-9551bd384f4e.PNG)
Ao testar os links é possível observar que eles estão funcionando, porém não reproduzem!

**Comment by Ramys** [comment]
Usa o vlc no windows...
E esse painel aqui para as listas.
http://webtv.iptvsmarters.com/index.php?adduser

**Comment by area189** [comment]
**Ambos OFF!** testado ontem dia 25.10.2022

any name :b5
login: x48yp
senha: 146QZQxgs
url: [http://acsc.cc:80](http://acsc.cc/)
-------------------------------------------
any name: axr
login: 00005733
senha: MF159357C
url: [http://axr.life:80](http://axr.life/)

**Comment by Ramys** [comment]
@area189 
Teste as outras listas.

**Comment by area189** [comment]
**Vou testar , retorno em breve**

**Comment by area189** [comment]
├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ fabio295
├🔸🔑 Senha➤ 27621572
├🔸📆 Exp.➤ 24-11-2022 20:47:03 

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ Enivaldo5824
├🔸🔑 Senha➤ 61999485824
├🔸📆 Exp.➤ 25-11-2022 07:15:59 

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ Marcao069
├🔸🔑 Senha➤ Manique069
├🔸📆 Exp.➤ 10-11-2022 19:28:25 
1
├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ luissantos
├🔸🔑 Senha➤ graniptv0110

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ bg605ct7to
├🔸🔑 Senha➤ x2d5ykzz70
├🔸📆 Exp.➤ 04-11-2022 10:31:12 

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ jumento
├🔸🔑 Senha➤ flavico
├🔸📆 Exp.➤ 03-06-2023 15:06:00 

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ Doraci064
├🔸🔑 Senha➤ Meirelles064
├🔸📆 Exp.➤ 04-11-2022 19:32:21
 
├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ mano18
├🔸🔑 Senha➤ 18mano167
├🔸📆 Exp.➤ 25-12-2022 11:30:24 
├🔸🌐 Host➤ http://srv.cldplay.net
2
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ sfxzg6kv25
├🔸🔑 Senha➤ 8ycr94rzp0
├🔸📆 Exp.➤ 01-12-2022 20:43:56 

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ doni@1
├🔸🔑 Senha➤ doni2021
├🔸📆 Exp.➤ 02-12-2022 20:19:13 

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ Frias81209012
├🔸🔑 Senha➤ gvk37kpr
├🔸📆 Exp.➤ 03-11-2022 19:08:30
 
├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ fernandotv11
├🔸🔑 Senha➤ 57954110
├🔸📆 Exp.➤ 02-11-2022 20:09:39 

├🔸🌐 Host➤ http://srv.cldplay.net
├🔸🌍 Real➤ http://srv.cldplay.net
├🔸📡 Port➤ 80
├🔸👩 Usuário➤ xub9821
├🔸🔑 Senha➤ XxubaZ23m
├🔸📆 Exp.➤ 06-11-2022 18:03:43

**Comment by Ramys** [comment]
http://srv.cldplay.net:80/get.php?username=fabio295&password=27621572&type=m3u
http://srv.cldplay.net:80/get.php?username=jumento&password=flavico&type=m3u  vencimento 03-06-2023 15:06:00
http://srv.cldplay.net:80/get.php?username=doni@1&password=doni2021&type=m3u 
http://srv.cldplay.net:80/get.php?username=mano18&password=18mano167&type=m3u

**Comment by Alissonfnxntc224** [comment]
area189 vc usa algum login na smart tv?

**Comment by Ramys** [comment]
https://github.com/Ramys/Iptv-Brasil-2022/issues/45
