### ISSUE TITLE
 usuário e a senha 

### ISSUE THREAD

**Issue by Etavares1301** [Ramys/Iptv-Brasil-2022#41]
Qual é o usuário e a senha para a lista: https://tinyurl.com/mpw3cvhr

**Comment by Ramys** [comment]
Sempre depois do :80/ 
Exemplo..http://vc.com:80/login/senha/778.ts

**Comment by Ramys** [comment]
Resolvido?

**Comment by area189** [comment]
@Ramys  encontrei algumas senhas para **IPTV SMARTERS** . Se quiser posso disponibilizar pra você.

**Comment by Ramys** [comment]
@area189 
Manda que eu baixo ela inteira e posto aqui pra vcs.
