### ISSUE TITLE
Duvidas com relação a IPTV

### ISSUE THREAD

**Issue by ZeReis1** [Ramys/Iptv-Brasil-2022#42]
Acredito que aqui não seja o lugar correto, mas gostaria de tirar umas duvidas com você caso seja possível.

Comprei uma smart tv recentemente e gostaria de conectar servidores de iptv nela.
Baixei um programa chamado smart tv club e fiz o upload de uma lista a ela.
No entanto, grande parte das listas exigem login e senha, porém não sei como fazer para logar.
Dessa forma, minhas duvidas são:

O programa iptv smarters que você deixou é pago? é possível criar um login gratis e carregar uma dessas listas que você disponibilizou? Essa senha que você deixou é para assistir sem precisar carregar as listas? Você usa algum outro programa além deste?

Desde já agradeço.

**Comment by Ramys** [comment]
Aqui nessa questão, tem uma explicação breve.
https://github.com/Ramys/Iptv-Brasil-2022/issues/41

**Comment by area189** [comment]
@Ramys  , CLUB TV consigo colocar as listas que você disponibilza? Pode colocar esse app pra download?

**Comment by Ramys** [comment]
@area189 
Somente lista deles..

**Comment by area189** [comment]
> @area189 Somente lista deles..

Ah sim , no caso lista paga , isso ?

**Comment by area189** [comment]
> Isso , ou achada na rede.

Ah sim , quando eu instalei e abri pediu usuário e senha.

**Comment by Ramys** [comment]
Usuário: 81827771

**Comment by Ramys** [comment]
> **Login Failed!** , deu erro e não entrou.

Login: : 4673629418

Senha : snakeplay

**Comment by area189** [comment]
> > **Login Failed!** , deu erro e não entrou.
> 
> Login: : 4673629418
> 
> Senha : snakeplay

Continua dando erro. 
Consegue disponibilizar o appk ?

**Comment by Ramys** [comment]
> > > **Login Failed!** , deu erro e não entrou.
> > 
> > 
> > Login: : 4673629418
> > Senha : snakeplay
> 
> Continua dando erro. Consegue disponibilizar o appk ?

Qual apk vc tá usando?

**Comment by Ramys** [comment]
https://github.com/Ramys/Iptv-Brasil-2022/issues/45
