### ISSUE TITLE
Pescagem

### ISSUE THREAD

**Issue by alanbonfim** [Ramys/Iptv-Brasil-2022#45]
Boa noite, como vc faz essas pescagem? Poderia passar quais programas?

https://github.com/Ramys/Iptv-Brasil-2022/issues/41 

Uso esse e o club tv , que é a mesma coisa praticamente.. 
O aplicativo é versão Pro , eu consegui através de um amigo e estou repassando...
As listas que estão aqui , eu encontro pescando com um programa que tenho, mas existem pessoas que vendem listas fixa e para várias conexões ou somente para um ip...dai cabe a vc comprar ou não , no caso em média a list custa 15~30 mensal..
No meu caso eu só repasso as que pesco na rede ;)

_Originally posted by @Ramys in https://github.com/Ramys/Iptv-Brasil-2022/issues/42#issuecomment-1292658215_

**Comment by Ramys** [comment]
Noite...
Amanhã eu farei um breve tuto explicando...
E postarei como pescar , achar e ver o limite de ip e etc... é simples , fácil e interessante...
;)

**Comment by area189** [comment]
> Noite... Amanhã eu farei um breve tuto explicando... E postarei como pescar , achar e ver o limite de ip e etc... é simples , fácil e interessante... ;)

Fiquei interessado! quero aprender.

**Comment by Lailsonfyy** [comment]
> Noite... Amanhã eu farei um breve tuto explicando... E postarei como pescar , achar e ver o limite de ip e etc... é simples , e interessante... ;)

E método de Google hacking procura por palavras chave em sites? Ou e programa específico tipo você encontra um site que tem a transmissão ao vivo e você pesca a URL através de programas?

**Comment by Ramys** [comment]
Tá meio corrido aqui pra mim , em breve eu ajudo vcs ...
É nois :)

**Comment by area189** [comment]
> Tá meio corrido aqui pra mim , em breve eu ajudo vcs ... É nois :)

Fala eu amigo , bom dia , Deixa cair no esquecimento não. =(

**Comment by area189** [comment]
Dá pra pescar http://cdnrede.com  ?!!!

**Comment by Ramys** [comment]
Aqui tem todas as listas de todos os países..
http://iptvhit.com/freeiptv?02/06/2022
