### ISSUE TITLE
Só 30 segundos por canal

### ISSUE THREAD

**Issue by felipeavilis** [Ramys/Iptv-Brasil-2022#46]
Os canais estão pegando perfeitamente, mas a cada 30 segundos ele vai para o próximo canal. Se eu coloco apenas 1 canal, diretamente a URL, ele toca por 30 e finaliza. Falta alguma configuração? O que estou fazendo de errado?

URL: http://axr.life:80/096154/686531/5262
OS: Windows 10
APP: VLC
VER: 3.0.17.4

Obrigado.

OBS: Parabéns pelo projeto.

**Comment by felipeavilis** [comment]
Instalei o IPTVSmartersPro e estou tendo o mesmo problema. Ele trava a cada 30seg.

**Comment by felipeavilis** [comment]
No VLC eu coloquei o vídeo em Loop, e reduzi o buffer. Deu uma melhorada, mas nao sei pq a transmissão termina em 30 segundos.... as vezes em 15, outras em 32...

**Comment by Ramys** [comment]
Deve ter muita gente on na lista

**Comment by Ramys** [comment]
Novas listas com várias conexões foram add..
