### ISSUE TITLE
Agradecimento

### ISSUE THREAD

**Issue by Robstabank** [Ramys/Iptv-Brasil-2022#47]
Olá Ramys, tudo bem? Eu de novo kkk
Só queria agradecer por essa "Lista Latino" que você disponibilizou pra gente. É de longe uma das melhores!!
Muito obrigado e um grande abraço!!
Tudo de bom!

**Comment by Ramys** [comment]
Opa....
Agradeço.
Assim que tiver mais tempo eu jogo mais listas no projeto..
