### ISSUE TITLE
Lista erro

### ISSUE THREAD

**Issue by BRUCKAO** [Ramys/Iptv-Brasil-2022#48]
Parou de funcionar -> 364648&.m3u8.m3u

**Maioria fora do ar**
Web Player iptvsmarters(02)
http://webtv.iptvsmarters.com/index.php?adduser
Qualquer Lista poderá ser adicionada no painel iptvsmarters.

Qualquer nome: Axr

Login: 096154

senha: 686531

url: [http://axr.life:80](http://axr.life/)

**Comment by Ramys** [comment]
> Parou de funcionar -> 364648&.m3u8.m3u
> 
> **Maioria fora do ar** Web Player iptvsmarters(02) http://webtv.iptvsmarters.com/index.php?adduser Qualquer Lista poderá ser adicionada no painel iptvsmarters.
> 
> Qualquer nome: Axr
> 
> Login: 096154
> 
> senha: 686531
> 
> url: [http://axr.life:80](http://axr.life/)
Parou de funcionar -> 364648&.m3u8.m3u
Lista Nova.
https://github.com/Ramys/Iptv-Brasil-2022/blob/master/1Lucilim.m3u
