### ISSUE TITLE
Lista não abre.

### ISSUE THREAD

**Issue by BRUCKAO** [Ramys/Iptv-Brasil-2022#49]
Caro amigo, obrigado pelo seu empenho em ajudar.

Informando que foi realizado o teste na 1Lucilim.m3u e não abriu.

Grande abraço.

**Comment by Ramys** [comment]
A lista está online , acabo de testa-la..
Quais programas vc usa para rodar a mesma?
Use um dos programas que disponibilizo no inicio do projeto.

**Comment by BRUCKAO** [comment]
Bom dia. Fiz o teste no IPTV Smarters Pro e no ato do teste realmente não funcionou, por isso informei aqui. Porém mais tarde fui verificar e funcionou normalmente. Pode ter sido algum erro de conexão. Te agradeço pelo empenho.

Recomenda algum outro aplicativo ?
