### ISSUE TITLE
Lista Canais KODI2.m3u8 e Globoplay no IPTV Smarterspro

### ISSUE THREAD

**Issue by brunobbarbosax** [Ramys/Iptv-Brasil-2022#50]
**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [por exemplo iOS]
 - Navegador [por exemplo, cromo, safári]
 - Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: [TV SAMSUNG]
 - SO: [Smart tv club / smarters pro ]
 - Navegador [por exemplo, navegador de ações, safári]
 - Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.
Boa tarde , prezado .

estava utilizando a lista Kodi no smart tv club , estava rodando perfeitamente, porém nas ultimas semanas parou de funcionar. 
o globoplay também não está funcionando no login e senha fornecido no smarterspro.

sei que fornece tudo de graça, caso não consiga me ajudar , não tem problema, mais se conseguir uma lista com o globoplay para nós, ficarei muito grato, e tenho certeza que muitas pessoas vão curtir também

**Comment by Ramys** [comment]
Opa....
Feliz natal , vou modificar e adicionar pra vcs.
