### ISSUE TITLE
Canais parando após 10s

### ISSUE THREAD

**Issue by arthuraltino** [Ramys/Iptv-Brasil-2022#7]
Os canais da lista B5 inicial a reprodução normalmente, porém param após uns 10 segundos.

**Comment by Ramys** [comment]
Qual lista B5?
@arthuraltino

**Comment by arthuraltino** [comment]
CanaisB5.m3u

**Comment by Ramys** [comment]
> CanaisB5.m3u
Se vc usa a lista no navegador , experimente instala o aplicativo em seu pc...
Link Iptv Stream Player : https://mega.nz/file/6htXCQ6Z#-Vn4GPhlEioREmUM6aTLcxaJ_v5IV3wruQhgzXh745M

**Comment by Ramys** [comment]
Resolvido?!
Caso esteja me avise que fecharei o ticket.

**Comment by arthuraltino** [comment]
No aplicativo tá funcionando normal! Alguma dessas listas usam a mesma fonte que o aplicativo?
Valeu demais!

**Comment by Ramys** [comment]
O B5 , somente da club...e o aplicativo deles ..
Já o app do PC , roda várias listas sem problemas...
Posso lhe passar o club tv , porém só roda com o dns deles .

**Comment by arthuraltino** [comment]
Se puder me passar ficaria grato.
Estou tentando colocar essas listas pra rodar em uma Apple TV antiga que tenho aqui, até agora nenhuma deu muito certo, e ela não roda app algum, só lista m3u8 mesmo.

**Comment by Ramys** [comment]
Consegue instalar app Android nele?

**Comment by arthuraltino** [comment]
Infelizmente, não. Ela é totalmente limitada.

**Comment by Ramys** [comment]
Esse aplicativo é para Android, pega em celular e tv box.
https://mega.nz/file/potQmLYJ#jyuLovZ6SxEzZxz_kP-XQxHDsxSkDEKcHWVTJQKZVKY

Vc poderia comprar uma tv box simples e usá-la..
Irei criar uma lista fluida somente em m3u8 , sem login apenas com url e lhe enviarei...
Estou finalizando , porém é somente canais..

**Comment by arthuraltino** [comment]
Excelente! É justamente o que eu preciso. Obrigado novamente!

**Comment by arthuraltino** [comment]
(Pode fechar o issue, se quiser)

**Comment by Ramys** [comment]
> (Pode fechar o issue, se quiser)
Teste esse no navegador Apple Tv.
http://playtv.si/index.php 

login: diegoeng
Senha: 809412

Acesso Válido Até: 06/03/2022 18:52:54
Restam: 12 Dias

**Comment by Ramys** [comment]
[arthuraltino](https://github.com/arthuraltino)
Me passa seu e-mail, irei lhe enviar os novos iptv m3u8 ..

**Comment by arthuraltino** [comment]
é o meu usuário arroba gmail
valeu!

**Comment by Ramys** [comment]
Teste ai e me faça!
[arthuraltino](https://github.com/arthuraltino)

**Comment by Mvmozzer** [comment]
Tem alguma lista m3u8 disponível que possa me enviar? eu gosto de usar o VLC na tv. 

Tu é o cara!! vlw por disponibilizar esses links!!
